trigger:
  branches:
    include:
    - experiment/ci

  paths:
    include:
    - walmart_sale_prediction.py

######################
# CI
######################

stages:
- stage: unitTests
  displayName:  running unit test config
  jobs:
  - job: setting_up_image
    continueOnError: false
    displayName: setting up image
    pool: # Change pool for local dev
      vmImage: ubuntu-latest


    steps:
    - script: env | sort
      displayName: 'Environment / Context'
        
    - task: UsePythonVersion@0
      displayName: Use Python 3.9
      inputs:
        versionSpec: '3.9'
        architecture: 'x64'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      clean: true
      persistCredentials: true

######################
# Code validation and unit tests
######################

    - script: |
        pip install -r ../requirements.txt
      displayName: install requiremetns
